import { MD5 } from "./md5_v1.js";
import { SHA256 } from "./sha256_v1.js";
import { cipher } from "./cipher_v1.js";
import { handleHTML, handleHTMLSubmit, toggleTTTOtherSeparator, handleTextToTableOptionsSubmit } from "./html_v1.js";
import { optimisecss, minifycss } from "./css_v1.js";
import { optimisejs, minifyjs } from "./js_v1.js";
import { handleLatex } from "./latex_v1.js";
import { fetchUrlToCurrentNote, openFetchModal, handleFetchSubmit } from "./fetch_v1.js";

window.MD5 = MD5;
window.SHA256 = SHA256;
window.cipher = cipher;
window.handleHTML = handleHTML;
window.handleHTMLSubmit = handleHTMLSubmit;
window.toggleTTTOtherSeparator = toggleTTTOtherSeparator;
window.handleTextToTableOptionsSubmit = handleTextToTableOptionsSubmit;
window.optimisecss = optimisecss;
window.minifycss = minifycss;
window.optimisejs = optimisejs;
window.minifyjs = minifyjs;
window.handleLatex = handleLatex;
window.fetchUrlToCurrentNote = fetchUrlToCurrentNote;
window.openFetchModal = openFetchModal;
window.handleFetchSubmit = handleFetchSubmit;
